/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.WriteMetaData;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.nio.file.DirectoryStream.Filter;
import java.util.Arrays;

/**
 *
 * @author Peke
 */
public class visualizador extends javax.swing.JFrame {
Lista list = new Lista();
Pdf aux;
Guardadatos f = new Guardadatos();
Edicion e = new Edicion();
    /**
     * Creates new form visualizador
     */
    public visualizador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        CargarBoton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TxtTamArchivo = new javax.swing.JTextField();
        TxtTamPaginas = new javax.swing.JTextField();
        TxtNoPaginas = new javax.swing.JTextField();
        TxtTitulo = new javax.swing.JTextField();
        TxtAsunto = new javax.swing.JTextField();
        TxtPClave = new javax.swing.JTextField();
        TxtAutor = new javax.swing.JTextField();
        TxtVersion = new javax.swing.JTextField();
        TxtApp = new javax.swing.JTextField();
        TxtImagenes = new javax.swing.JTextField();
        TxtFuentes = new javax.swing.JTextField();
        EditarBoton = new javax.swing.JToggleButton();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 51, 51));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        CargarBoton.setBackground(new java.awt.Color(255, 255, 0));
        CargarBoton.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        CargarBoton.setText("Cargar");
        CargarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarBotonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel1.setText("Nombre de archivo:");

        TxtNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 3, 48)); // NOI18N
        jLabel3.setText("METADATOS");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 3, 48)); // NOI18N
        jLabel4.setText("FLMC");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel5.setText("TAMAÑO DEL ARCHIVO:");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel6.setText("TAMAÑO DE PAGINAS:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel7.setText("No PAGINAS:");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel8.setText("TITULO:");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel9.setText("ASUNTO:");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel10.setText("Autor");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel11.setText("PALABRA CLAVE:");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel12.setText("APLICACION DE ORIGEN:");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel13.setText("VERSION DE PDF:");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel14.setText("FUENTES:");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel15.setText("IMAGENES:");

        EditarBoton.setBackground(new java.awt.Color(255, 255, 0));
        EditarBoton.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        EditarBoton.setText("EDITAR Y GUARDAR");
        EditarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TxtAsunto)
                                    .addComponent(TxtTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtNoPaginas, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtTamPaginas, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtTamArchivo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtPClave, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtAutor)
                            .addComponent(TxtVersion)
                            .addComponent(TxtApp)
                            .addComponent(TxtImagenes)
                            .addComponent(TxtFuentes)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(CargarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(796, 796, 796))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(CargarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(EditarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTamArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTamPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNoPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtFuentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtPClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    
    private void CargarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarBotonActionPerformed
        String nombre;
        String path;
        JFileChooser pdfruta = new JFileChooser();
        pdfruta.setDialogTitle("Seleccione el archivo");
        pdfruta.setFileSelectionMode(JFileChooser.APPROVE_OPTION);
        if(pdfruta.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            File archivo = pdfruta.getSelectedFile();
            nombre = pdfruta.getName(archivo);           
            TxtNombre.setText(nombre); 
            TxtTitulo.setText(nombre); 
            if(archivo.isDirectory()){
                leerDatos(archivo);
            } else if (archivo.isFile()){
                leerArchivosPDF(archivo);
            }
        }
    }//GEN-LAST:event_CargarBotonActionPerformed

    private void EditarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBotonActionPerformed
 
        
       aux.setTamArchivo(TxtTamArchivo.getText());
        String TamArchivoE = TxtTamArchivo.getText();
        aux.setTamPaginas(TxtTamPaginas.getText());
        String TamPaginasE = TxtTamPaginas.getText();
        aux.setNoPaginas(TxtNoPaginas.getText());
        String NoPaginasE = TxtNoPaginas.getText();
        aux.setTitulo(TxtTitulo.getText());
        String TituloE = TxtTitulo.getText();
        aux.setAsunto(TxtAsunto.getText());
        String AsuntoE = TxtAsunto.getText();
        aux.setPClave(TxtPClave.getText());
        String PClaveE = TxtPClave.getText(); 
       aux.setTipo(TxtAutor.getText());
        String TipoE = TxtAutor.getText();
       aux.setVersion(TxtVersion.getText());
        String VersionE = TxtVersion.getText();
       aux.setApp(TxtApp.getText());
        String AppE = TxtApp.getText();
        aux.setImagenes(TxtImagenes.getText());
        String ImagenesE = TxtImagenes.getText();
        aux.setFuentes(TxtFuentes.getText());
        String FuentesE = TxtFuentes.getText();
       
        aux = aux.getSiguiente();
        
        
        //String TamArchivo,String TamPaginas,String NoPaginas,String Titulo,String Asunto, String PClave,String Tipo,String version,String app,String imagenes,String fuentes){
      
        list.agregarAlInicio(TamArchivoE, TamPaginasE + "m.m", NoPaginasE, TituloE, AsuntoE, PClaveE, TipoE, VersionE, AppE, ImagenesE, FuentesE);
        e.edicion(list);
                                               

    }//GEN-LAST:event_EditarBotonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visualizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visualizador().setVisible(true);
            }
        });
    }
    
    private void leerDatos(File archivo){
        String temp = "";
        for (final File fileEntry : archivo.listFiles()){
            if (fileEntry.isDirectory()) {
                leerDatos(fileEntry);
            } else {
                if (fileEntry.isFile()) {
                    temp = fileEntry.getName();
                    if ((temp.substring(temp.lastIndexOf('.') + 1, temp.length()).toLowerCase()).equals("pdf")){
                        TxtNombre.setText(fileEntry.getName());
                        TxtTitulo.setText(fileEntry.getName());
                        String auxiliar = archivo.getAbsolutePath()+ "\\" + fileEntry.getName();
                        File archivopdf = new File(auxiliar);
                        leerArchivosPDF(archivopdf);                     
                    }
                }
            }
        }
    }
     
    private void leerArchivosPDF(File archivo){
        Leer nuevoPDF = new Leer(archivo);
        int a = nuevoPDF.MetadataFinder().split("/").length;
        String[] partir = nuevoPDF.MetadataFinder().split("/");
        String Autor = "--";
        String Creador = "--";
        int contador = 0;
        for(int j=1; j<a; j++){
            if (contador == 0){
                Autor = partir[j];  
            }
            else if (contador ==1){
                Creador = partir[j]; 
            }
            contador = contador +1;
        }
        int noPaginas = nuevoPDF.NumPagFinder();
        int noImagenes = nuevoPDF.ImagenesFinder();
        TxtAutor.setText(Autor);
        TxtApp.setText(Creador);
        TxtVersion.setText(nuevoPDF.VersionFinder());
        TxtTamArchivo.setText(nuevoPDF.TamanoFinder());        
        String p = Integer.toString(noPaginas);
        TxtNoPaginas.setText(p);
        TxtTamPaginas.setText(nuevoPDF.TamPagFinder() + " mm");
        String i = Integer.toString(noImagenes);
        TxtImagenes.setText(i);
        TxtFuentes.setText(nuevoPDF.FuentesFinder());
        list.agregarAlInicio(nuevoPDF.TamanoFinder(), nuevoPDF.TamPagFinder() + "mm", p,"titulo" , "---", "---", Autor, nuevoPDF.VersionFinder(), Creador, i, nuevoPDF.FuentesFinder());
        f.escribit(list);
        System.out.println("Guardado Exitosamente");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CargarBoton;
    private javax.swing.JToggleButton EditarBoton;
    private javax.swing.JTextField TxtApp;
    private javax.swing.JTextField TxtAsunto;
    private javax.swing.JTextField TxtAutor;
    private javax.swing.JTextField TxtFuentes;
    private javax.swing.JTextField TxtImagenes;
    private javax.swing.JTextField TxtNoPaginas;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtPClave;
    private javax.swing.JTextField TxtTamArchivo;
    private javax.swing.JTextField TxtTamPaginas;
    private javax.swing.JTextField TxtTitulo;
    private javax.swing.JTextField TxtVersion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
